[scheme]
name = "Earthtone Light"
author = "vaporif@proton.me"

[palette]
base00 = "e8dcc6" # bg — main background
base01 = "f8f1de" # bg_dim — panels, sidebars
base02 = "d5c9b8" # bg_visual — selection
base03 = "9da9a0" # comment — comments, invisibles
base04 = "72817a" # stone_grey — dark fg, status bars
base05 = "3e474d" # fg — default foreground
base06 = "565047" # driftwood — light fg
base07 = "534241" # charcoal — darkest neutral
base08 = "a2362f" # brick — red
base09 = "a66130" # warm_orange — orange
base0A = "725926" # toffee — yellow
base0B = "607530" # olive — green
base0C = "2c7670" # teal — cyan
base0D = "264d8a" # function_deep — blue
base0E = "8c3f65" # plum — purple
base0F = "859289" # river_stone — brown
