[colors]
foreground = "#3e474d"
background = "#e8dcc6"
cursor_fg = "#e8dcc6"
cursor_bg = "#3e474d"
selection_fg = "#3e474d"
selection_bg = "#d5c9b8"

ansi = [
  "#3e474d",  # black (fg)
  "#924e4c",  # red (brick)
  "#71844d",  # green (olive)
  "#765e36",  # yellow (toffee)
  "#536568",  # blue (storm_blue)
  "#765a67",  # magenta (plum)
  "#63847e",  # cyan (teal)
  "#b5c1b8",  # white (pale_stone)
]

brights = [
  "#72817a",  # bright black (stone_grey)
  "#9d4746",  # bright red (coral)
  "#71844d",  # bright green (olive)
  "#b06d47",  # bright yellow (warm_orange)
  "#536568",  # bright blue (storm_blue)
  "#765a67",  # bright magenta (plum)
  "#63847e",  # bright cyan (teal)
  "#f8f1de",  # bright white (bg_dim)
]

[metadata]
name = "earthtone-light"
