[colors]
foreground = "#3e474d"
background = "#e8dcc6"
cursor_fg = "#e8dcc6"
cursor_bg = "#3e474d"
selection_fg = "#3e474d"
selection_bg = "#d5c9b8"

ansi = [
  "#3e474d",  # black (fg)
  "#ab605d",  # red (brick)
  "#89a05d",  # green (olive)
  "#bb9c68",  # yellow (honey)
  "#70888b",  # blue (storm_blue)
  "#7f616e",  # magenta (plum)
  "#71958e",  # cyan (aqua)
  "#b5c1b8",  # white (pale_stone)
]

brights = [
  "#7d8d85",  # bright black (stone_grey)
  "#b96361",  # bright red (coral)
  "#89a05d",  # bright green (olive)
  "#c08563",  # bright yellow (warm_orange)
  "#70888b",  # bright blue (storm_blue)
  "#7f616e",  # bright magenta (plum)
  "#71958e",  # bright cyan (aqua)
  "#f8f1de",  # bright white (bg_dim)
]

[metadata]
name = "earthtone"
